export const styles = {
  container: {
    display: "flex",
    justifyContent: "center",
    padding: 20,
    marginTop: 70,
  },
  card: {
    width: "100%",
    maxWidth: 500,
    border: "1px solid #eee",
    padding: 30,
    borderRadius: 12,
    background: "#fff",
    boxShadow: "0 4px 20px rgba(0,0,0,0.08)",
  },
  title: {
    margin: "0 0 10px 0",
  },
  img: {
    width: "100%",
    height: "250px",
    objectFit: "cover",
    borderRadius: 10,
  },
  description: {
    fontSize: 14,
    color: "#4a4a4a",
    lineHeight: "1.6",
    margin: "10px 0",
  },
  price: {
    fontSize: 14,
    fontWeight: "600",
    color: "gray",
  },
  location: {
    fontSize: 13,
    color: "#6b6b6b",
    marginTop: 4,
  },
  btnContainer: {
    marginTop: 15,
    display: "flex",
    gap: 10,
  },
  editBtn: {
    flex: 1,
    padding: 10,
    background: "#007bff",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    cursor: "pointer",
  },
  deleteBtn: {
    flex: 1,
    padding: 10,
    background: "#ff385c",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    cursor: "pointer",
  },
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    background: "rgba(0,0,0,0.5)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  modal: {
    background: "#fff",
    padding: 25,
    borderRadius: 10,
    width: 300,
    textAlign: "center",
  },
  modalBtns: {
    display: "flex",
    gap: 10,
  },
  cancelBtn: {
    flex: 1,
    padding: 10,
    background: "#ccc",
    border: "none",
    borderRadius: 6,
    cursor: "pointer",
  },
  confirmBtn: {
    flex: 1,
    padding: 10,
    background: "#ff385c",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    cursor: "pointer",
  },
};
